### ISSUE TITLE
Incorporate VoxelMorph into evaluation of registration methods

### ISSUE THREAD

**Issue by ebrahimebrahim** [brain-microstructure-exploration-tools/abcd-registration-experiments#22]

**Comment by jamesfishbaugh** [comment]
The open issue regarding voxelmorph is the output deformation and it's format.

- Voxelmorph documentation refers to it as a _deformation_ field but in my experiments I recall it to be a _displacement_ field. This should be double checked.
- We should double check if the displacement field is in voxel or scanner units and if the evaluation framework is handling the units correctly.

**Comment by ebrahimebrahim** [comment]
Double checked an output: Indeed it is a displacement field. The voxelmorph documentation probably meant that as "deformation field" is a bit ambiguous.

(Still looking into the voxel vs scanner units question)
