### ISSUE TITLE
Add additional evaluation criteria/metrics

### ISSUE THREAD

**Issue by jamesfishbaugh** [brain-microstructure-exploration-tools/abcd-registration-experiments#23]

**Comment by ebrahimebrahim** [comment]
the goal is (1) - (5) listed [here](https://github.com/brain-microstructure-exploration-tools/abcd-registration-experiments/issues/13#issuecomment-2072719558):

> 1. Tract distance (mean closest fiber distance) 
> 1. Tract dice (overlap of binary tract segmentation masks) 
> 1. Tract volumetric similarity (for a non-overlap measurement of binary tract segmentation masks) 
> 1. Jacobian of deformation field (percentage of voxels with non-positive determinant) 
> 1. Runtime
