### ISSUE TITLE
Develop method for evaluating pairwise dmri registration models

### ISSUE THREAD

**Issue by ebrahimebrahim** [brain-microstructure-exploration-tools/abcd-registration-experiments#3]
We can talk about how to approach this but my current thought is to approach this in a way that uses template construction.

A generic way to go from a pairwise registration algorithm to a template construction algorithm is to use the classic Joshi-style iteration (as described in @jamesfishbaugh's [presentation](https://docs.google.com/presentation/d/1MmS4NVpQ3cUO8eD0XVxxQ2wbAcCIst3huTK011rIgFI/edit?usp=drive_link)). Template construction will be both (a) an important step in our pipeline and (b) a possibly very useful step for the evaluation of our registration methodology.

In order to use template construction when evaluating and comparing different pairwise registration algorithms we'd like to have a script/function that can accept a generic pairwise registration function and a set of multichannel scalar images and does Joshi-style iterative template construction, generating a template and a collection of warps to that template.

**Comment by ebrahimebrahim** [comment]
Inputs should be 

- a pairwise registration function (a function that accepts two images and returns at least a displacement field)
- a set of scalar (possibly multi-channel) images 

Outputs

- a template image
- deformations to the template

**Comment by ebrahimebrahim** [comment]
Here is my current idea for how to approach this:

![](https://github.com/brain-microstructure-exploration-tools/abcd-registration-experiments/assets/1879759/686f9d3c-4834-4ea2-912b-c8392f191bf0)

- `template.py` stands for a script to be written here that takes a set of multichannel scalar images and a pariwise registration function as input, does Joshi style iterative template construction, and generates a template and a collection of warps to that template. Warps should be in a format mrtrix would understand. The pairwise registration function needs to be able to handle blurry images.
- the first `mrtrix` step is to use `mrtransform` to warp all the subject fods to the same space, and then to average them using `mrmath`. you can see [here](https://github.com/MRtrix3/mrtrix3/blob/325dcc1244fc5de796ad52f29f78a834cd7d7736/bin/population_template#L192) how `population_template` is doing its aggregation step.
- the second `mrtrix` step does tractography in the template space using `tckgen`.
- `analysis.py` stands for a script we will write that takes a set of scalar subject images (say FA) and a tract in template space and a set of warps from the subject image to the template space. these ingredients can give a set of tract profiles of the scalar (e.g. FA) along the tract in the subject space. then we look at the intersubject variance of the scalar along the tract. the result is a set of functions of a tract parameter $t$ that output variance $\sigma^2$. these can be aggregated to generate an overall intersubject variance score. a registration algorithm is better at aligning tracts if this aggregate variance is smaller.
- there are some subtleties not included in the diagram:
	- masks need to be carried around. probably should warp masks to template space and intersect them all to get a mask template.
	- before using `mrmath` to average images in the first `mrtrix` step, we might want to normalize the fods. otherwise the fods that seem to be large for no reason would be weighted higher in the average. fod magnitude seems to be very scanner dependent. does it matter if we normalize the fods before or after warping them? would be good to check.
	- the second `mrtrix` step with the tractography is going to require thinking about how to seed it, where to get the tracts, etc. might need to bring an atlas with some seed points on it or something.

**Comment by ebrahimebrahim** [comment]
Registration algorithms to include in the evaluations:

- Ours
- DTI-TK
- ANTs -- FA
- ANTs -- FA + MD
- VoxelMorph -- FA (but maybe it should be b0? check Zhang paper)
- mrtrix - FOD
- [DDMReg](https://github.com/zhangfanmark/DDMReg) (but this requires generating TOMs which may or may not be difficult)


Thinking about these, I think on second thought that a generic `template.py` doesn't makes sense

The real goal is to generate the warps for each of these methods that we include in the evaluation.

![image](https://github.com/brain-microstructure-exploration-tools/abcd-registration-experiments/assets/1879759/d208b419-5cf6-42d6-842a-5be3af4cc086)

**Comment by ebrahimebrahim** [comment]
After a research group meeting we are now thinking differently. Here is a summary:

- We want to aim for an evaluation approach that does not involve any kind of population template construction. If it works good, if not then we can go back to the template construction ideas.
- We will apply our evaluation to each pair of images. So if there are $n$ images that's $n^2$ evaluations. To make this tractable either $n$ will have to be small or the registration and evaluation will have to be fast.
- Evaluation on a pair of subject images will involve registering one image to another and doing tractography in both images, and then measuring somehow the alignment of the tracts.
- Problem: How do we seed tractography in each subject image without ever registering to a template? Should we actually do _whole brain_ tractography? i.e. using WM as seed? Should connectivity or streamline count somehow then be the thing we compare between subject pairs? If so then same problem: where will the ROIs come from without ever registering to a template?

**Comment by ebrahimebrahim** [comment]
This can be considered complete when there is at least one pathway (possibly consisting of many disparate scripts) that takes us from at least one pairwise registration method to a score that describes the quality of tract alignment.

**Comment by jamesfishbaugh** [comment]
I have finished a script (or yes, a collection of scripts) which starts from dwi images and outputs fiber tract scores using ANTs (w/ fa images). It is light on error checking, creates several temporary files, and uses some hardcoded filenames. It may be good enough for our evaluation purposes or we can address these issues.

**Comment by ebrahimebrahim** [comment]
It looks good, I'll test it out! Merging first and if I suggest any changes it'll be in my own PR.
