### ISSUE TITLE
Create tract warping figure for the progress report

### ISSUE THREAD

**Issue by jamesfishbaugh** [brain-microstructure-exploration-tools/abcd-registration-experiments#9]
I've been working on the progress report and could use a figure that helps describe our evaluation methodology.

It'd be nice to show 3D views of fiber bundles as follows for two subjects:

- subject A's fiber bundle in subject A's space
- subject B's fiber bundle in subject B's space
- subject B's fiber bundle warped into subject A's space
- subject A's fiber bundle and the warped subject B fiber bundle in different colors, both in subject A's space

We could use for example the [AF](https://en.wikipedia.org/wiki/Arcuate_fasciculus) for this demo, or whatever

**Comment by jamesfishbaugh** [comment]
Here is the current version of the figure. 

![Image](https://github.com/brain-microstructure-exploration-tools/abcd-registration-experiments/assets/12160522/f6f01551-9ef6-49df-8dfe-7ae84db7d349)

**Comment by ebrahimebrahim** [comment]
Beautiful! Is that paraview for the lower ones?

How's this for a caption:

> Fiber tracts being warped in order to be compared via a tract distance metric. This is an example of the AF tract from two subjects in our processed data, with a bundle being warped along the whole-image registration transform between the subjects.

Please feel free to edit the caption here on [on overleaf](https://www.overleaf.com/project/660190782b1ea15587211001) (ask for invite if i havent sent it)

**Comment by ebrahimebrahim** [comment]
Could add the svg to [graphics drive folder](https://drive.google.com/drive/u/0/folders/1_kcyWOl8PBxSzGNpNozd60EElugfzHdL)

**Comment by jamesfishbaugh** [comment]
I do need an invite for overleaf (jfishbaugh@gmail.com).
